version: '3.9'

services:
  auth_db:
    image: postgres:16
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    restart: always
    depends_on:
      - auth_db
    ports:
      - "8001:8000"
    env_file:
      - ./auth_service/.env
    volumes:
      - ./auth_service:/app

volumes:
  auth_db_data:
